# Generated by Django 2.2.4 on 2019-08-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_user_token_valid_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_expiration',
            field=models.DateTimeField(blank=True, help_text='Password reset tokens will only be valid until this timestamp.', null=True, verbose_name='password reset expiration'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.UUIDField(blank=True, null=True, verbose_name='password reset token'),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_valid_timestamp',
            field=models.DateTimeField(blank=True, help_text='Tokens with an `iat` field before this timestamp will not validate.', null=True, verbose_name='token valid timestamp'),
        ),
    ]
