# Generated by Django 2.2.4 on 2019-10-14 12:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20191014_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='client',
            name='token',
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=uuid.UUID('c507de72-18c7-4ede-ac1c-95ede827665a'), max_length=255, unique=True, verbose_name='client ID'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_secret',
            field=models.CharField(default=uuid.UUID('545278ac-709a-497b-a82d-bd5aef001901'), max_length=255, unique=True, verbose_name='client secret'),
        ),
    ]
