# Generated by Django 2.2.4 on 2019-10-29 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20191015_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_id',
            field=models.CharField(default=uuid.UUID('6577296f-7560-4f2e-9cfa-3b3d874e086c'), help_text='We use a different ID than the object ID to preserve database security', max_length=255, unique=True, verbose_name='client ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_secret',
            field=models.CharField(default=uuid.UUID('a94bb40a-ac98-4dd6-a99b-da1e6188d012'), max_length=255, unique=True, verbose_name='client secret'),
        ),
        migrations.CreateModel(
            name='DefaultTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
